/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as LobbyRouteImport } from './routes/lobby'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlaySoloRouteImport } from './routes/play/solo'
import { Route as PlayRoomCodeRouteImport } from './routes/play/$roomCode'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbyRoute = LobbyRouteImport.update({
  id: '/lobby',
  path: '/lobby',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaySoloRoute = PlaySoloRouteImport.update({
  id: '/play/solo',
  path: '/play/solo',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoomCodeRoute = PlayRoomCodeRouteImport.update({
  id: '/play/$roomCode',
  path: '/play/$roomCode',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/lobby': typeof LobbyRoute
  '/menu': typeof MenuRoute
  '/profile': typeof ProfileRoute
  '/play/$roomCode': typeof PlayRoomCodeRoute
  '/play/solo': typeof PlaySoloRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/lobby': typeof LobbyRoute
  '/menu': typeof MenuRoute
  '/profile': typeof ProfileRoute
  '/play/$roomCode': typeof PlayRoomCodeRoute
  '/play/solo': typeof PlaySoloRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/lobby': typeof LobbyRoute
  '/menu': typeof MenuRoute
  '/profile': typeof ProfileRoute
  '/play/$roomCode': typeof PlayRoomCodeRoute
  '/play/solo': typeof PlaySoloRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/leaderboard'
    | '/lobby'
    | '/menu'
    | '/profile'
    | '/play/$roomCode'
    | '/play/solo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/leaderboard'
    | '/lobby'
    | '/menu'
    | '/profile'
    | '/play/$roomCode'
    | '/play/solo'
  id:
    | '__root__'
    | '/'
    | '/leaderboard'
    | '/lobby'
    | '/menu'
    | '/profile'
    | '/play/$roomCode'
    | '/play/solo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LobbyRoute: typeof LobbyRoute
  MenuRoute: typeof MenuRoute
  ProfileRoute: typeof ProfileRoute
  PlayRoomCodeRoute: typeof PlayRoomCodeRoute
  PlaySoloRoute: typeof PlaySoloRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobby': {
      id: '/lobby'
      path: '/lobby'
      fullPath: '/lobby'
      preLoaderRoute: typeof LobbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/solo': {
      id: '/play/solo'
      path: '/play/solo'
      fullPath: '/play/solo'
      preLoaderRoute: typeof PlaySoloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$roomCode': {
      id: '/play/$roomCode'
      path: '/play/$roomCode'
      fullPath: '/play/$roomCode'
      preLoaderRoute: typeof PlayRoomCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LeaderboardRoute: LeaderboardRoute,
  LobbyRoute: LobbyRoute,
  MenuRoute: MenuRoute,
  ProfileRoute: ProfileRoute,
  PlayRoomCodeRoute: PlayRoomCodeRoute,
  PlaySoloRoute: PlaySoloRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
